name: 自动检测更新并打包 Spider Jar

# 只要代码一更新，立刻自动打包
on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: 拉取最新代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 配置 JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: 执行自动打包
        run: call buildAndGenJar.bat ec
        shell: cmd

      - name: 提交新版本 Jar 到仓库
        uses: EndBug/add-and-commit@v9
        with:
          message: "CI 自动构建：更新 spider jar"
          add: "jar/*.jar jar/*.md5"
          default_author: github_actions
     
